[workspace]
authors = ["sunbei00 <sunbei00@naver.com>"]
channels = ["conda-forge"]
name = "gs"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

# ===========================================================

[environments]
gs = {features=["gs"], no-default-feature=true}
orbslam2 = {features = ["orbslam2"], no-default-feature = true}

# ===========================================================

[feature.gs]
channels = ["conda-forge"]

[feature.gs.system-requirements]
cuda="11.8"

[feature.gs.dependencies]
cuda-version="11.8*"
pytorch-gpu="==2.0.0"
viser="*"
imageio-ffmpeg="*"
numpy="<2.0.0"
scipy="*"
tqdm="*"
torchmetrics="*"
py-opencv="*"
tyro=">=0.8.8"
pillow="*"
tensorboard="*"
tensorly="*"
pyyaml="*"
matplotlib="*"
splines="*"
pip="*"
jaxtyping="*"
ninja="*"
scikit-learn="*"
unzip="*"
torchvision="*"


[feature.gs.pypi-dependencies]
nerfview = { git = "https://github.com/nerfstudio-project/nerfview", rev = "4538024fe0d15fd1a0e4d760f3695fc44ca72787" }
fused-ssim = {git = "https://github.com/rahul-goel/fused-ssim", rev ="328dc9836f513d00c4b5bc38fe30478b4435cbb5"}
fused-bilagrid = {git = "https://github.com/harry7557558/fused-bilagrid", rev="90f9788e57d3545e3a033c1038bb9986549632fe"}
nerfacc = {git = "git+https://github.com/nerfstudio-project/nerfacc"}
pycolmap={git = "https://github.com/rmbrualla/pycolmap", rev="cc7ea4b7301720ac29287dbe450952511b32125e"}

[feature.gs.pypi-options]
no-build-isolation = ["fused-bilagrid", "fused-ssim", "nerfacc"]

# ---- Feature: orbslam2 ----
[feature.orbslam2]
channels = [
    "https://prefix.dev/sunbei",
  "https://fast.prefix.dev/conda-forge",
  "https://prefix.dev/conda-forge",
  "conda-forge",
]
platforms = ["linux-64"]

[feature.orbslam2.dependencies]
pangolin = { version = "==0.5.0", build = "3" }
libxcrypt = "*"
gcc             = "8.*"
gxx             = "*"
cmake           = ">=3.16"
ninja           = "*"
make            = "*"
pkg-config      = "*"
jpeg   = "*"

eigen           = ">=3.1.0"
opencv          = ">=3.2.0,<4.0.0"
boost-cpp       = "*"
yaml-cpp        = "*"
libjpeg-turbo   = "*"
libpng          = "*"
ffmpeg = "==4.1.3"

glew            = "*"
libgl-devel     = "*"
libglu          = "*"
libegl          = "*"
xorg-libx11     = "*"
xorg-libxrandr  = "*"

python          = "3.7.*"          
pip             = "*"

